spring:
  application:
    name: sample-spring-elasticsearch
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:11027
  elasticsearch:
    rest:
      uris: http://localhost:11027

initial-import:
  enabled: false